### ISSUE TITLE
2022 春节特别节目 lightning talk

### ISSUE THREAD

**Issue by jiacai2050** [EmacsTalk/joinus#12]
- 形式：使用腾讯会议（加入方式见下），所有道友都可以加入。会有视频录制，事后会放出来。
- 主题：分享自己的 Emacs 配置、插件、折腾心得、新年展望等等，与 Emacs 有关的内容即可
- 时长：5-15分钟内（根据时间，会有 QA 环节）
- 时间：2021-02-13 19:00--21:00（春假放假后的那个周日）

# 报名方式
在这个 issue **留言** ，备注下 talk 主题。其他观众可以给感兴趣的 Talk 点赞 👍，点赞数决定出场次序。

方便的话可以加下听友群：
- QQ： 530146104
- TG：https://t.me/emacstalk

# 说明
- 如果不方便，可以采用事前录制的方式，到时候我来播放
- 论坛的帖子：https://emacs-china.org/t/emacstalk-2022-lightning-talk

# 加入方式

会议主题：EmacsTalk 2022 特别节目
会议时间：2022/02/13 19:00-21:30 (GMT+08:00) 中国标准时间 - 北京

点击链接入会，或添加至会议列表：
https://meeting.tencent.com/dm/Un5AzziaxtpL

腾讯会议：164-337-909

复制该信息，打开手机腾讯会议即可参与

**Comment by lujun9972** [comment]
org-mode与habitica的联动之旅

**Comment by condy0919** [comment]
还行，主题就是分享一下自己的 Emacs 配置 https://github.com/condy0919/.emacs.d

**Comment by BlindingDark** [comment]
主题: Vterm 与 Emacs 交互。
或安利 Telega

**Comment by tshu-w** [comment]
主题：ebib, citar, org-roam

**Comment by Ilgharkus** [comment]
想分享一下自己用 org+yasnippet+cdlatex 练习速记数学笔记的折腾之旅。

**Comment by yibie** [comment]
分享一下非编程专业的人如何使用 Emacs？以及这么多年折腾的工具

**Comment by Elilif** [comment]
分享一下用emms.el+lyrics-fetcher.el+picard来管理自己的本地音乐库

**Comment by beyondpie** [comment]
你好，海外想旁听，但是时间上不太合适，是否会提供录制后可播放的链接？

**Comment by jiacai2050** [comment]
@beyondpie 会有的，第一条就写了
> 形式：使用腾讯会议（加入方式见下），所有道友都可以加入。会有视频录制，事后会放出来。

**Comment by jiacai2050** [comment]
截止到 2022-02-11 21:09 为止，报名结束，感谢上面道友的捧场。下面是分享的顺序，请大家不要忘了，周日晚 7 点，不见不散。

# 出场顺序
| 顺序 | ID            | 主题                                              |
|--- |------------- |------------------------------------------------- |
| 1  | @Ilgharkus    | org+yasnippet+cdlatex 练习速记数学笔记的折腾之旅  |
| 2  | @lujun9972    | org-mode与habitica的联动之旅                      |
| 3  | @condy0919    | Emacs [配置](https://github.com/condy0919/.emacs.d) |
| 4  | @BlindingDark | Vterm 与 Emacs 交互                               |
| 5  | @Elilif       | emms.el+lyrics-fetcher.el+picard来管理自己的本地音乐库 |
| 6  | @tshu-w       | ebib, citar, org-roam                             |
| 7  | @yibie        | 非编程专业的人如何使用 Emacs                      |

**Comment by jiacai2050** [comment]
- https://github.com/EmacsTalk/2022-lightingtalks

各位嘉宾的 slides 可以上传到这个仓库

**Comment by jiacai2050** [comment]
会议完美结束，感谢大家捧场支持。下面是视频回放地址：
- https://www.bilibili.com/video/BV1Mr4y1a7JT/
![Snip20220213_1](https://user-images.githubusercontent.com/3848910/153760210-c79f1607-5e88-4b2d-9714-7ce346a3e7a1.png)

**Comment by jiacai2050** [comment]
- https://www.youtube.com/watch?v=J42NoXH35Vk

<img width="529" alt="image" src="https://user-images.githubusercontent.com/3848910/155884050-b3666a61-0b31-4a23-8ac6-af0cde39b3b2.png">

Youtube 上传了下，加上了时间线，比 B 站好些。

- 00:00 org+yasnippet+cdlatex 练习速记数学笔记的折腾之旅 by Ilgharkus
- 29:33 org-mode与habitica的联动之旅 by lujun9972
- 44:15 Emacs 内置包介绍 by condy0919
- 1:10:21 Vterm 与 Emacs 交互 by BlindingDark
- 1:21:20 emms.el+lyrics-fetcher.el+picard来管理自己的本地音乐库 by Elilif
- 1:34:07 ebib, citar, org-roam by tshu-w
- 1:49:23 非编程专业的人如何使用 Emacs by yibie
- 2:22:52 个人 emacs 配置介绍 by 西瓜
- 2:29:03 org 如何处理任务依赖关系 by lujun9972
- 2:31:00 telega 介绍 by BlindingDark
- 2:39:49 闲聊

**Comment by brucejuz** [comment]
各位大虾，能不能出一个详细一点的教程，这个talk里面有点听不懂啊。
尤其是ebib, citar, zotero, org-roam, 之间文献管理，笔记的联动，能不能详细介绍一下，多谢！

**Comment by tshu-w** [comment]
@brucejuz 教程我短期应该没空写，不过你真要感兴趣等我忙完年前投稿可以私下给你介绍下
